//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_CHAR
    {
        public string strAccountID { get; set; }
        public byte bNation { get; set; }
        public byte bCharNum { get; set; }
        public string strCharID1 { get; set; }
        public string strCharID2 { get; set; }
        public string strCharID3 { get; set; }
        public string strCharID4 { get; set; }
    }
}
