//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEGINNER_ITEM
    {
        public short iClass { get; set; }
        public string strClass { get; set; }
        public long Gold { get; set; }
        public string strItem { get; set; }
        public byte[] strItem1 { get; set; }
    }
}
