//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Panel_Duyrular
    {
        public int id { get; set; }
        public string baslik { get; set; }
        public string detay { get; set; }
        public int durum { get; set; }
        public int etkinlik { get; set; }
        public int duyuru { get; set; }
        public System.DateTime tarih { get; set; }
    }
}
