//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class COEFFICIENT
    {
        public short sClass { get; set; }
        public double ShortSword { get; set; }
        public double Sword { get; set; }
        public double Axe { get; set; }
        public double Club { get; set; }
        public double Spear { get; set; }
        public double Pole { get; set; }
        public double Staff { get; set; }
        public Nullable<double> Bow { get; set; }
        public double Hp { get; set; }
        public double Mp { get; set; }
        public double Sp { get; set; }
        public double Ac { get; set; }
        public double Hitrate { get; set; }
        public double Evasionrate { get; set; }
    }
}
