//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCURRENT
    {
        public byte serverid { get; set; }
        public short zone1_count { get; set; }
        public short zone2_count { get; set; }
        public short zone3_count { get; set; }
    }
}
