//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeathLOG
    {
        public int sIndex { get; set; }
        public Nullable<int> Zone { get; set; }
        public string Zaman { get; set; }
        public string Olduren { get; set; }
        public Nullable<int> Oldurenin_irki { get; set; }
        public Nullable<int> Oldurenin_OncekiNP { get; set; }
        public Nullable<int> Oldurenin_SonrakiNP { get; set; }
        public Nullable<int> Oldurenin_KazandigiNP { get; set; }
        public string Oldurulen { get; set; }
        public Nullable<int> Oldurulen_irki { get; set; }
        public Nullable<int> Oldurulen_OncekiNP { get; set; }
        public Nullable<int> Oldurulen_SonrakiNP { get; set; }
        public string Olduren_PT1 { get; set; }
        public string Olduren_PT2 { get; set; }
        public string Olduren_PT3 { get; set; }
        public string Olduren_PT4 { get; set; }
        public string Olduren_PT5 { get; set; }
        public string Olduren_PT6 { get; set; }
        public string Olduren_PT7 { get; set; }
        public string Olduren_PT8 { get; set; }
    }
}
