//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELLOS_TAX
    {
        public string strAccountID { get; set; }
        public string strCharID { get; set; }
        public int nTax { get; set; }
        public int nUserMoney { get; set; }
    }
}
