//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESN_KOD
    {
        public int id { get; set; }
        public string esnkod { get; set; }
        public string passkod1 { get; set; }
        public string passkod2 { get; set; }
        public decimal fiyat { get; set; }
        public bool durum { get; set; }
        public string straccountid { get; set; }
    }
}
