//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public byte ZoneNum { get; set; }
        public short EventNum { get; set; }
        public byte Type { get; set; }
        public string Cond1 { get; set; }
        public string Cond2 { get; set; }
        public string Cond3 { get; set; }
        public string Cond4 { get; set; }
        public string Cond5 { get; set; }
        public string Exec1 { get; set; }
        public string Exec2 { get; set; }
        public string Exec3 { get; set; }
        public string Exec4 { get; set; }
        public string Exec5 { get; set; }
    }
}
