//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_TIMES
    {
        public short sIndex { get; set; }
        public byte bTime1 { get; set; }
        public byte bTime2 { get; set; }
        public byte bTime3 { get; set; }
        public byte bLvMin { get; set; }
        public byte bLVMax { get; set; }
        public string EventName { get; set; }
        public byte AllDays { get; set; }
    }
}
