//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRIEND_LIST
    {
        public string strUserID { get; set; }
        public string strFriend1 { get; set; }
        public string strFriend2 { get; set; }
        public string strFriend3 { get; set; }
        public string strFriend4 { get; set; }
        public string strFriend5 { get; set; }
        public string strFriend6 { get; set; }
        public string strFriend7 { get; set; }
        public string strFriend8 { get; set; }
        public string strFriend9 { get; set; }
        public string strFriend10 { get; set; }
        public string strFriend11 { get; set; }
        public string strFriend12 { get; set; }
        public string strFriend13 { get; set; }
        public string strFriend14 { get; set; }
        public string strFriend15 { get; set; }
        public string strFriend16 { get; set; }
        public string strFriend17 { get; set; }
        public string strFriend18 { get; set; }
        public string strFriend19 { get; set; }
        public string strFriend20 { get; set; }
        public string strFriend21 { get; set; }
        public string strFriend22 { get; set; }
        public string strFriend23 { get; set; }
        public string strFriend24 { get; set; }
    }
}
