//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_EXCHANGE
    {
        public int nIndex { get; set; }
        public short nNpcNum { get; set; }
        public string strNpcName { get; set; }
        public string strNote { get; set; }
        public byte bRandomFlag { get; set; }
        public int nOriginItemNum1 { get; set; }
        public short nOriginItemCount1 { get; set; }
        public int nOriginItemNum2 { get; set; }
        public short nOriginItemCount2 { get; set; }
        public int nOriginItemNum3 { get; set; }
        public short nOriginItemCount3 { get; set; }
        public int nOriginItemNum4 { get; set; }
        public short nOriginItemCount4 { get; set; }
        public int nOriginItemNum5 { get; set; }
        public short nOriginItemCount5 { get; set; }
        public int nOriginItemNum6 { get; set; }
        public short nOriginItemCount6 { get; set; }
        public int nOriginItemNum7 { get; set; }
        public short nOriginItemCount7 { get; set; }
        public int nOriginItemNum8 { get; set; }
        public short nOriginItemCount8 { get; set; }
        public int nOriginItemNum9 { get; set; }
        public short nOriginItemCount9 { get; set; }
        public int nOriginItemNum10 { get; set; }
        public short nOriginItemCount10 { get; set; }
        public int nOriginItemNum11 { get; set; }
        public short nOriginItemCount11 { get; set; }
        public int nExchangeItemNum1 { get; set; }
        public short nExchangeItemCount1 { get; set; }
        public int nExchangeItemNum2 { get; set; }
        public short nExchangeItemCount2 { get; set; }
        public int nExchangeItemNum3 { get; set; }
        public short nExchangeItemCount3 { get; set; }
        public int nExchangeItemNum4 { get; set; }
        public short nExchangeItemCount4 { get; set; }
        public int nExchangeItemNum5 { get; set; }
        public short nExchangeItemCount5 { get; set; }
    }
}
