//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_GROUP
    {
        public short group { get; set; }
        public string name { get; set; }
        public int item1 { get; set; }
        public int item2 { get; set; }
        public int item3 { get; set; }
        public int item4 { get; set; }
        public int item5 { get; set; }
        public int item6 { get; set; }
        public int item7 { get; set; }
        public int item8 { get; set; }
        public int item9 { get; set; }
        public int item10 { get; set; }
        public int item11 { get; set; }
        public int item12 { get; set; }
        public int item13 { get; set; }
        public int item14 { get; set; }
        public int item15 { get; set; }
        public int item16 { get; set; }
        public int item17 { get; set; }
        public int item18 { get; set; }
        public int item19 { get; set; }
        public int item20 { get; set; }
        public int item21 { get; set; }
        public int item22 { get; set; }
        public int item23 { get; set; }
        public int item24 { get; set; }
        public int item25 { get; set; }
        public int item26 { get; set; }
        public int item27 { get; set; }
        public int item28 { get; set; }
        public int item29 { get; set; }
        public int item30 { get; set; }
    }
}
