//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_UPGRADE33
    {
        public int nIndex { get; set; }
        public short nNPCNum { get; set; }
        public string strName { get; set; }
        public string strNote { get; set; }
        public short nOriginType { get; set; }
        public int nOriginItem { get; set; }
        public int nReqItem1 { get; set; }
        public int nReqItem2 { get; set; }
        public int nReqItem3 { get; set; }
        public int nReqItem4 { get; set; }
        public int nReqItem5 { get; set; }
        public int nReqItem6 { get; set; }
        public int nReqItem7 { get; set; }
        public int nReqItem8 { get; set; }
        public int nReqNoah { get; set; }
        public byte bRateType { get; set; }
        public short nGenRate { get; set; }
        public int nGiveItem { get; set; }
    }
}
