//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_OP
    {
        public int nItemID { get; set; }
        public byte bTriggerType { get; set; }
        public int nSkillID { get; set; }
        public byte bTriggerRate { get; set; }
    }
}
