//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMUP_PROBABILITY
    {
        public byte bType { get; set; }
        public short nMaxSuccess { get; set; }
        public short nMaxFail { get; set; }
        public short nCurSuccess { get; set; }
        public short nCurFail { get; set; }
    }
}
