//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_MONSTER
    {
        public short sSid { get; set; }
        public string strName { get; set; }
        public short sPid { get; set; }
        public short sSize { get; set; }
        public int iWeapon1 { get; set; }
        public int iWeapon2 { get; set; }
        public byte byGroup { get; set; }
        public byte byActType { get; set; }
        public byte byType { get; set; }
        public byte byFamily { get; set; }
        public byte byRank { get; set; }
        public byte byTitle { get; set; }
        public int iSellingGroup { get; set; }
        public short sLevel { get; set; }
        public int iExp { get; set; }
        public int iLoyalty { get; set; }
        public int iHpPoint { get; set; }
        public short sMpPoint { get; set; }
        public short sAtk { get; set; }
        public short sAc { get; set; }
        public short sHitRate { get; set; }
        public short sEvadeRate { get; set; }
        public short sDamage { get; set; }
        public short sAttackDelay { get; set; }
        public short sSpeed { get; set; }
        public byte bySpeed1 { get; set; }
        public byte bySpeed2 { get; set; }
        public short sStandtime { get; set; }
        public short sItem { get; set; }
        public int iMagic1 { get; set; }
        public int iMagic2 { get; set; }
        public int iMagic3 { get; set; }
        public short sFireR { get; set; }
        public short sColdR { get; set; }
        public short sLightningR { get; set; }
        public short sMagicR { get; set; }
        public short sDiseaseR { get; set; }
        public short sPoisonR { get; set; }
        public short sLightR { get; set; }
        public short sBulk { get; set; }
        public byte byAttackRange { get; set; }
        public byte bySearchRange { get; set; }
        public byte byTracingRange { get; set; }
        public int iMoney { get; set; }
        public byte byDirectAttack { get; set; }
        public byte byMagicAttack { get; set; }
        public byte byMoneyType { get; set; }
    }
}
