//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_NPC_ITEM
    {
        public short sIndex { get; set; }
        public int iItem01 { get; set; }
        public Nullable<short> sPersent01 { get; set; }
        public Nullable<int> iItem02 { get; set; }
        public Nullable<short> sPersent02 { get; set; }
        public Nullable<int> iItem03 { get; set; }
        public Nullable<short> sPersent03 { get; set; }
        public Nullable<int> iItem04 { get; set; }
        public Nullable<short> sPersent04 { get; set; }
        public Nullable<int> iItem05 { get; set; }
        public Nullable<short> sPersent05 { get; set; }
    }
}
