//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_OBJECTPOS
    {
        public short ZoneID { get; set; }
        public byte Belong { get; set; }
        public short sIndex { get; set; }
        public byte Type { get; set; }
        public short ControlNpcID { get; set; }
        public byte Status { get; set; }
        public double PosX { get; set; }
        public double PosY { get; set; }
        public double PosZ { get; set; }
        public byte byLife { get; set; }
    }
}
