//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_OBJECTEVENT
    {
        public short sZoneNo { get; set; }
        public short sIndex { get; set; }
        public byte byLife { get; set; }
        public short sBelong { get; set; }
        public short sType { get; set; }
        public short sControlNpcId { get; set; }
        public short sStatus { get; set; }
        public short sPosX { get; set; }
        public short sPosY { get; set; }
        public short sPosZ { get; set; }
    }
}
