//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KING_SYSTEM
    {
        public byte byNation { get; set; }
        public byte byType { get; set; }
        public short sYear { get; set; }
        public byte byMonth { get; set; }
        public byte byDay { get; set; }
        public byte byHour { get; set; }
        public byte byMinute { get; set; }
        public byte byImType { get; set; }
        public short sImYear { get; set; }
        public byte byImMonth { get; set; }
        public byte byImDay { get; set; }
        public byte byImHour { get; set; }
        public byte byImMinute { get; set; }
        public byte byNoahEvent { get; set; }
        public byte byNoahEvent_Day { get; set; }
        public byte byNoahEvent_Hour { get; set; }
        public byte byNoahEvent_Minute { get; set; }
        public short sNoahEvent_Duration { get; set; }
        public byte byExpEvent { get; set; }
        public byte byExpEvent_Day { get; set; }
        public byte byExpEvent_Hour { get; set; }
        public byte byExpEvent_Minute { get; set; }
        public short sExpEvent_Duration { get; set; }
        public int nTribute { get; set; }
        public byte byTerritoryTariff { get; set; }
        public int nTerritoryTax { get; set; }
        public int nNationalTreasury { get; set; }
        public string strKingName { get; set; }
        public string strImRequestID { get; set; }
    }
}
