//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KING_CANDIDACY_NOTICE_BOARD
    {
        public string strUserID { get; set; }
        public byte byNation { get; set; }
        public short sNoticeLen { get; set; }
        public byte[] strNotice { get; set; }
    }
}
