//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNIGHTS_CAPE
    {
        public short sCapeIndex { get; set; }
        public string strName { get; set; }
        public int nBuyPrice { get; set; }
        public int nDuration { get; set; }
        public byte byGrade { get; set; }
        public int nBuyLoyalty { get; set; }
        public byte byRanking { get; set; }
    }
}
