//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNIGHT
    {
        public short IDNum { get; set; }
        public byte Flag { get; set; }
        public byte Nation { get; set; }
        public byte Ranking { get; set; }
        public string IDName { get; set; }
        public short Members { get; set; }
        public string Chief { get; set; }
        public string ViceChief_1 { get; set; }
        public string ViceChief_2 { get; set; }
        public string ViceChief_3 { get; set; }
        public long Gold { get; set; }
        public short Domination { get; set; }
        public int Points { get; set; }
        public byte[] Mark { get; set; }
        public short sMarkVersion { get; set; }
        public short sMarkLen { get; set; }
        public short sCape { get; set; }
        public byte bCapeR { get; set; }
        public byte bCapeG { get; set; }
        public byte bCapeB { get; set; }
        public short sAllianceKnights { get; set; }
        public int ClanPointFund { get; set; }
        public string strClanNotice { get; set; }
        public byte bySiegeFlag { get; set; }
        public short nLose { get; set; }
        public short nVictory { get; set; }
        public byte ClanPointMethod { get; set; }
        public System.DateTime dtCreateTime { get; set; }
        public short nWarEnemyID { get; set; }
        public string strEnemyName { get; set; }
        public byte byOldWarResult { get; set; }
    }
}
