//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNIGHTS_RATING
    {
        public int nRank { get; set; }
        public short shIndex { get; set; }
        public string strName { get; set; }
        public int nPoints { get; set; }
        public int nClanPointFund { get; set; }
    }
}
