//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KNIGHTS_SIEGE_WARFARE
    {
        public short sCastleIndex { get; set; }
        public short sMasterKnights { get; set; }
        public byte bySiegeType { get; set; }
        public byte byWarDay { get; set; }
        public byte byWarTime { get; set; }
        public byte byWarMinute { get; set; }
        public short sChallengeList_1 { get; set; }
        public short sChallengeList_2 { get; set; }
        public short sChallengeList_3 { get; set; }
        public short sChallengeList_4 { get; set; }
        public short sChallengeList_5 { get; set; }
        public short sChallengeList_6 { get; set; }
        public short sChallengeList_7 { get; set; }
        public short sChallengeList_8 { get; set; }
        public short sChallengeList_9 { get; set; }
        public short sChallengeList_10 { get; set; }
        public byte byWarRequestDay { get; set; }
        public byte byWarRequestTime { get; set; }
        public byte byWarRequestMinute { get; set; }
        public byte byGuerrillaWarDay { get; set; }
        public byte byGuerrillaWarTime { get; set; }
        public byte byGuerrillaWarMinute { get; set; }
        public string strChallengeList { get; set; }
        public short sMoradonTariff { get; set; }
        public short sDellosTariff { get; set; }
        public int nDungeonCharge { get; set; }
        public int nMoradonTax { get; set; }
        public int nDellosTax { get; set; }
        public short sRequestList_1 { get; set; }
        public short sRequestList_2 { get; set; }
        public short sRequestList_3 { get; set; }
        public short sRequestList_4 { get; set; }
        public short sRequestList_5 { get; set; }
        public short sRequestList_6 { get; set; }
        public short sRequestList_7 { get; set; }
        public short sRequestList_8 { get; set; }
        public short sRequestList_9 { get; set; }
        public short sRequestList_10 { get; set; }
    }
}
