//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_DONATIONS
    {
        public int id { get; set; }
        public string key { get; set; }
        public short type { get; set; }
        public short state { get; set; }
        public string account { get; set; }
        public float worth { get; set; }
        public int points { get; set; }
        public int timestamp { get; set; }
        public string fieldAlfa { get; set; }
        public string fieldBravo { get; set; }
    }
}
