//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_LOGIN
    {
        public int id { get; set; }
        public string account { get; set; }
        public string ip { get; set; }
        public string host { get; set; }
        public string browser { get; set; }
        public int timestamp { get; set; }
    }
}
