//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_BANS
    {
        public int banid { get; set; }
        public string account { get; set; }
        public int before { get; set; }
        public int now { get; set; }
        public string byadmin { get; set; }
        public System.DateTime datetime { get; set; }
        public string reason { get; set; }
    }
}
