//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_SENDITEM
    {
        public int sid { get; set; }
        public string von { get; set; }
        public string an { get; set; }
        public string itemname { get; set; }
        public int count { get; set; }
        public int upgrade { get; set; }
        public int element { get; set; }
        public int elementupgrade { get; set; }
        public int piercing { get; set; }
    }
}
