//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ITEMS
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Command { get; set; }
        public string Image { get; set; }
        public int Cost { get; set; }
        public int Level { get; set; }
        public int Job { get; set; }
    }
}
