//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGIC_TYPE72004
    {
        public int nIndex { get; set; }
        public string strName { get; set; }
        public string strNote { get; set; }
        public byte byValidGroup { get; set; }
        public byte byNatoinChange { get; set; }
        public short shMonsterNum { get; set; }
        public byte byTargetChange { get; set; }
        public byte byStateChange { get; set; }
        public byte byRadius { get; set; }
        public short shHitrate { get; set; }
        public short shDuration { get; set; }
        public short shDamage { get; set; }
        public byte byVisoin { get; set; }
        public int nNeedItem { get; set; }
    }
}
