//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGIC_TYPE1orj
    {
        public int iNum { get; set; }
        public byte Type { get; set; }
        public short HitRate { get; set; }
        public short Hit { get; set; }
        public short AddDamage { get; set; }
        public byte Delay { get; set; }
        public byte ComboType { get; set; }
        public byte ComboCount { get; set; }
        public short ComboDamage { get; set; }
        public short Range { get; set; }
        public short unk1 { get; set; }
        public short unk2 { get; set; }
        public short unk3 { get; set; }
        public short unk4 { get; set; }
    }
}
