//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGIC
    {
        public int MagicNum { get; set; }
        public string EnName { get; set; }
        public string KrName { get; set; }
        public string Description { get; set; }
        public int BeforeAction { get; set; }
        public byte TargetAction { get; set; }
        public byte SelfEffect { get; set; }
        public short FlyingEffect { get; set; }
        public short TargetEffect { get; set; }
        public byte Moral { get; set; }
        public short SkillLevel { get; set; }
        public short Skill { get; set; }
        public short Msp { get; set; }
        public short HP { get; set; }
        public byte ItemGroup { get; set; }
        public int UseItem { get; set; }
        public short CastTime { get; set; }
        public short ReCastTime { get; set; }
        public short SuccessRate { get; set; }
        public byte Type1 { get; set; }
        public byte Type2 { get; set; }
        public short Range { get; set; }
        public byte UseStanding { get; set; }
        public short Etc { get; set; }
    }
}
