//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGIC_TYPE2
    {
        public int iNum { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte HitType { get; set; }
        public short HitRate { get; set; }
        public short AddDamage { get; set; }
        public short AddRange { get; set; }
        public byte NeedArrow { get; set; }
    }
}
