//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGIC_TYPE62004
    {
        public int iNum { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public short Size { get; set; }
        public short TransformID { get; set; }
        public short Duration { get; set; }
        public short MaxHp { get; set; }
        public short MaxMp { get; set; }
        public byte Speed { get; set; }
        public short AttackSpeed { get; set; }
        public short TotalHit { get; set; }
        public short TotalAc { get; set; }
        public short TotalHitRate { get; set; }
        public short TotalEvasionRate { get; set; }
        public short TotalFireR { get; set; }
        public short TotalColdR { get; set; }
        public short TotalLightningR { get; set; }
        public short TotalMagicR { get; set; }
        public short TotalDiseaseR { get; set; }
        public short TotalPoisonR { get; set; }
        public short Class { get; set; }
        public byte UserSkillUse { get; set; }
        public byte NeedItem { get; set; }
        public byte SkillSuccessRate { get; set; }
        public byte MonsterFriendly { get; set; }
        public byte Nation { get; set; }
    }
}
