//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGIC_TYPE9son
    {
        public int iNum { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte ValidGroup { get; set; }
        public byte NationChange { get; set; }
        public short MonsterNum { get; set; }
        public byte TargetChange { get; set; }
        public byte StateChange { get; set; }
        public short Radius { get; set; }
        public short Hitrate { get; set; }
        public short Duration { get; set; }
        public short AddDamage { get; set; }
        public short Vision { get; set; }
        public int NeedItem { get; set; }
    }
}
