//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGIC_TYPE3orj
    {
        public int iNum { get; set; }
        public byte Radius { get; set; }
        public byte DirectType { get; set; }
        public short FirstDamage { get; set; }
        public short TimeDamage { get; set; }
        public byte Duration { get; set; }
        public byte Attribute { get; set; }
        public Nullable<short> EndDamage { get; set; }
        public Nullable<short> Angle { get; set; }
    }
}
