//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAGIC_TYPE8
    {
        public int iNum { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte Target { get; set; }
        public short Radius { get; set; }
        public byte WarpType { get; set; }
        public short ExpRecover { get; set; }
        public short KickDistance { get; set; }
    }
}
