//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL_BOX
    {
        public int nLetterID { get; set; }
        public System.DateTime dtSendDate { get; set; }
        public Nullable<System.DateTime> dtReadDate { get; set; }
        public byte bStatus { get; set; }
        public string strSenderID { get; set; }
        public string strRecipientID { get; set; }
        public string strSubject { get; set; }
        public string strMessage { get; set; }
        public byte bType { get; set; }
        public int nItemID { get; set; }
        public short sCount { get; set; }
        public short sDurability { get; set; }
        public long nSerialNum { get; set; }
        public int nCoins { get; set; }
        public bool bDeleted { get; set; }
    }
}
