//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL_ITEM
    {
        public int ID { get; set; }
        public Nullable<byte> Status { get; set; }
        public string sId { get; set; }
        public string tId { get; set; }
        public string Title { get; set; }
        public Nullable<byte> bAccess { get; set; }
        public string Content { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<int> Gold { get; set; }
        public Nullable<int> nNum { get; set; }
        public Nullable<short> sCount { get; set; }
        public Nullable<System.DateTime> sTime { get; set; }
        public Nullable<byte> bDay { get; set; }
    }
}
