//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAKE_ITEM_GROUP
    {
        public int iItemGroupNum { get; set; }
        public int iItem_1 { get; set; }
        public int iItem_2 { get; set; }
        public int iItem_3 { get; set; }
        public int iItem_4 { get; set; }
        public int iItem_5 { get; set; }
        public int iItem_6 { get; set; }
        public int iItem_7 { get; set; }
        public int iItem_8 { get; set; }
        public int iItem_9 { get; set; }
        public int iItem_10 { get; set; }
        public int iItem_11 { get; set; }
        public int iItem_12 { get; set; }
        public int iItem_13 { get; set; }
        public int iItem_14 { get; set; }
        public int iItem_15 { get; set; }
        public int iItem_16 { get; set; }
        public int iItem_17 { get; set; }
        public int iItem_18 { get; set; }
        public int iItem_19 { get; set; }
        public int iItem_20 { get; set; }
        public int iItem_21 { get; set; }
        public int iItem_22 { get; set; }
        public int iItem_23 { get; set; }
        public int iItem_24 { get; set; }
        public int iItem_25 { get; set; }
        public int iItem_26 { get; set; }
        public int iItem_27 { get; set; }
        public int iItem_28 { get; set; }
        public int iItem_29 { get; set; }
        public int iItem_30 { get; set; }
    }
}
