//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAKE_ITEM_LARECODE
    {
        public byte byLevelGrade { get; set; }
        public short sUpgradeItem { get; set; }
        public short sLareItem { get; set; }
        public short sMagicItem { get; set; }
        public short sGereralItem { get; set; }
    }
}
