//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAKE_WEAPON
    {
        public byte byLevel { get; set; }
        public Nullable<short> sClass_1 { get; set; }
        public Nullable<short> sClass_2 { get; set; }
        public Nullable<short> sClass_3 { get; set; }
        public Nullable<short> sClass_4 { get; set; }
        public Nullable<short> sClass_5 { get; set; }
        public Nullable<short> sClass_6 { get; set; }
        public Nullable<short> sClass_7 { get; set; }
        public Nullable<short> sClass_8 { get; set; }
        public Nullable<short> sClass_9 { get; set; }
        public Nullable<short> sClass_10 { get; set; }
        public Nullable<short> sClass_11 { get; set; }
        public Nullable<short> sClass_12 { get; set; }
    }
}
