//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAKE_ITEM_GRADECODE
    {
        public byte byItemIndex { get; set; }
        public short byGrade_1 { get; set; }
        public Nullable<short> byGrade_2 { get; set; }
        public Nullable<short> byGrade_3 { get; set; }
        public Nullable<short> byGrade_4 { get; set; }
        public Nullable<short> byGrade_5 { get; set; }
        public Nullable<short> byGrade_6 { get; set; }
        public Nullable<short> byGrade_7 { get; set; }
        public Nullable<short> byGrade_8 { get; set; }
        public Nullable<short> byGrade_9 { get; set; }
    }
}
