//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINING_ITEM
    {
        public int nItemID { get; set; }
        public int nCount { get; set; }
        public short nRate { get; set; }
        public byte nZoneID { get; set; }
        public byte bNation { get; set; }
    }
}
