//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIXING_ITEM
    {
        public int nIndex { get; set; }
        public int nRobItem1 { get; set; }
        public short nRobItemCount1 { get; set; }
        public int nRobItem2 { get; set; }
        public short nRobItemCount2 { get; set; }
        public int nRobItem3 { get; set; }
        public short nRobItemCount3 { get; set; }
        public int nRobItem4 { get; set; }
        public short nRobItemCount4 { get; set; }
        public int nRobItem5 { get; set; }
        public short nRobItemCount5 { get; set; }
        public int nRobItem6 { get; set; }
        public short nRobItemCount6 { get; set; }
        public int nRobItem7 { get; set; }
        public short nRobItemCount7 { get; set; }
        public int nRobItem8 { get; set; }
        public short nRobItemCount8 { get; set; }
        public int nRobItem9 { get; set; }
        public short nRobItemCount9 { get; set; }
        public int nRobItem10 { get; set; }
        public short nRobItemCount10 { get; set; }
        public int nGiveItem1 { get; set; }
        public short nGiveItemCount1 { get; set; }
        public int nGiveItem2 { get; set; }
        public short nGiveItemCount2 { get; set; }
        public int nGiveItem3 { get; set; }
        public short nGiveItemCount3 { get; set; }
        public int nGiveItem4 { get; set; }
        public short nGiveItemCount4 { get; set; }
        public int nGiveItem5 { get; set; }
        public short nGiveItemCount5 { get; set; }
        public int nGiveItem6 { get; set; }
        public short nGiveItemCount6 { get; set; }
        public int nGiveItem7 { get; set; }
        public short nGiveItemCount7 { get; set; }
        public int nGiveItem8 { get; set; }
        public short nGiveItemCount8 { get; set; }
        public int nGiveItem9 { get; set; }
        public short nGiveItemCount9 { get; set; }
        public int nGiveItem10 { get; set; }
        public short nGiveItemCount10 { get; set; }
        public short nRate { get; set; }
    }
}
