//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVCPanelReference
    {
        public string Servername { get; set; }
        public string LisenceKey { get; set; }
        public string YouTube { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Twic { get; set; }
    }
}
