//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYPAL_LOG
    {
        public int id { get; set; }
        public string StrAccountID { get; set; }
        public string txid { get; set; }
        public string tutar { get; set; }
        public string payment_status { get; set; }
        public string item_name { get; set; }
        public string receiver_email { get; set; }
        public string payer_email { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
