//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREMIUM_SERVICE_USER
    {
        public string strClientID { get; set; }
        public System.DateTime timeReg { get; set; }
        public Nullable<System.DateTime> timeValid { get; set; }
        public Nullable<byte> bCurrent { get; set; }
    }
}
