//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREMIUM_ITEM_EXP
    {
        public short nIndex { get; set; }
        public byte Type { get; set; }
        public byte MinLevel { get; set; }
        public byte MaxLevel { get; set; }
        public short sPercent { get; set; }
    }
}
