//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREMIUM_ITEM
    {
        public byte Type { get; set; }
        public short ExpRestorePercent { get; set; }
        public short NoahPercent { get; set; }
        public short DropPercent { get; set; }
        public int BonusLoyalty { get; set; }
        public short RepairDiscountPercent { get; set; }
        public short ItemSellPercent { get; set; }
    }
}
