//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUS_ITEMS
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public string strItemName { get; set; }
        public string strItemTitle { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> DcPrice { get; set; }
        public string Image { get; set; }
        public Nullable<int> SendType { get; set; }
        public Nullable<int> ItemType { get; set; }
        public int BuyCount { get; set; }
    }
}
