//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUS_CASH
    {
        public int cashid { get; set; }
        public int Total { get; set; }
        public int Cash { get; set; }
        public string Aciklama { get; set; }
        public int PID { get; set; }
    }
}
