//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUS_SESSION
    {
        public string strAccountID { get; set; }
        public string strUserID { get; set; }
        public string strClass { get; set; }
        public string strLevel { get; set; }
        public string strParam { get; set; }
        public Nullable<System.DateTime> strData { get; set; }
        public int id { get; set; }
    }
}
