//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUS_LOG
    {
        public int ID { get; set; }
        public Nullable<byte> Progress_Type { get; set; }
        public string Session_ID { get; set; }
        public Nullable<int> Old_CashPoint { get; set; }
        public Nullable<int> Old_BonusCash { get; set; }
        public Nullable<int> New_CashPoint { get; set; }
        public Nullable<int> New_BonusCashPoint { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public Nullable<int> Progress_Result { get; set; }
        public System.DateTime Progress_Date { get; set; }
    }
}
