//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEST_HELPERusko
    {
        public int nIndex { get; set; }
        public byte bMessageType { get; set; }
        public byte bLevel { get; set; }
        public int nExp { get; set; }
        public byte bClass { get; set; }
        public byte bNation { get; set; }
        public byte bQuestType { get; set; }
        public byte bZone { get; set; }
        public short sNpcId { get; set; }
        public short sEventDataIndex { get; set; }
        public byte bEventStatus { get; set; }
        public int nEventTriggerIndex { get; set; }
        public int nEventCompleteIndex { get; set; }
        public int nExchangeIndex { get; set; }
        public int nEventTalkIndex { get; set; }
        public string strLuaFilename { get; set; }
    }
}
