//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUEST_MONSTER
    {
        public short sQuestNum { get; set; }
        public short sNum1a { get; set; }
        public short sNum1b { get; set; }
        public short sNum1c { get; set; }
        public short sNum1d { get; set; }
        public short sCount1 { get; set; }
        public short sNum2a { get; set; }
        public short sNum2b { get; set; }
        public short sNum2c { get; set; }
        public short sNum2d { get; set; }
        public short sCount2 { get; set; }
        public short sNum3a { get; set; }
        public short sNum3b { get; set; }
        public short sNum3c { get; set; }
        public short sNum3d { get; set; }
        public short sCount3 { get; set; }
        public short sNum4a { get; set; }
        public short sNum4b { get; set; }
        public short sNum4c { get; set; }
        public short sNum4d { get; set; }
        public short sCount4 { get; set; }
    }
}
