//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEALED_ITEMS
    {
        public int ID { get; set; }
        public string strAccountID { get; set; }
        public string strUserID { get; set; }
        public long nItemSerial { get; set; }
        public int nItemID { get; set; }
        public byte bSealType { get; set; }
    }
}
