//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SET_ITEM
    {
        public int SetIndex { get; set; }
        public string SetName { get; set; }
        public short ACBonus { get; set; }
        public short HPBonus { get; set; }
        public short MPBonus { get; set; }
        public short StrengthBonus { get; set; }
        public short StaminaBonus { get; set; }
        public short DexterityBonus { get; set; }
        public short IntelBonus { get; set; }
        public short CharismaBonus { get; set; }
        public short FlameResistance { get; set; }
        public short GlacierResistance { get; set; }
        public short LightningResistance { get; set; }
        public short PoisonResistance { get; set; }
        public short MagicResistance { get; set; }
        public short CurseResistance { get; set; }
        public short XPBonusPercent { get; set; }
        public short CoinBonusPercent { get; set; }
        public short APBonusPercent { get; set; }
        public short APBonusClassType { get; set; }
        public short APBonusClassPercent { get; set; }
        public short ACBonusClassType { get; set; }
        public short ACBonusClassPercent { get; set; }
        public short MaxWeightBonus { get; set; }
        public byte NPBonus { get; set; }
        public byte Unk10 { get; set; }
        public byte Unk11 { get; set; }
        public byte Unk12 { get; set; }
        public byte Unk13 { get; set; }
        public byte Unk14 { get; set; }
        public byte Unk15 { get; set; }
        public byte Unk16 { get; set; }
        public byte Unk17 { get; set; }
        public byte Unk18 { get; set; }
        public byte Unk19 { get; set; }
        public byte Unk20 { get; set; }
        public byte Unk21 { get; set; }
    }
}
