//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOP_ITEMLIST
    {
        public int mid { get; set; }
        public int itemid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int priceDP { get; set; }
        public int count { get; set; }
        public int category { get; set; }
        public string icon { get; set; }
        public string effects { get; set; }
        public Nullable<byte> currency { get; set; }
        public int priceVP { get; set; }
    }
}
