//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_NEWS_MAIN
    {
        public int id { get; set; }
        public string titletr { get; set; }
        public string newstr { get; set; }
        public string titleen { get; set; }
        public string newsen { get; set; }
        public string titlees { get; set; }
        public string newses { get; set; }
        public Nullable<int> newsid { get; set; }
        public Nullable<int> newsimage { get; set; }
    }
}
