//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class START_POSITION
    {
        public short ZoneID { get; set; }
        public short sKarusX { get; set; }
        public short sKarusZ { get; set; }
        public short sElmoradX { get; set; }
        public short sElmoradZ { get; set; }
        public Nullable<short> sKarusGateX { get; set; }
        public Nullable<short> sKarusGateZ { get; set; }
        public Nullable<short> sElmoGateX { get; set; }
        public Nullable<short> sElmoGateZ { get; set; }
        public byte bRangeX { get; set; }
        public byte bRangeZ { get; set; }
    }
}
