//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNDER_MONSTER_CHALLENGE_SUMMON_LIST
    {
        public short sIndex { get; set; }
        public byte bLevel { get; set; }
        public byte bStage { get; set; }
        public byte bStageLevel { get; set; }
        public short sTime { get; set; }
        public short sSid { get; set; }
        public string strName { get; set; }
        public short sCount { get; set; }
        public short sPosX { get; set; }
        public short sPosZ { get; set; }
        public byte bRange { get; set; }
    }
}
