//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNDER_MONSTER_CHALLENGE
    {
        public short sIndex { get; set; }
        public byte bStartTime1 { get; set; }
        public byte bStartTime2 { get; set; }
        public byte bStartTime3 { get; set; }
        public byte bLevelMin { get; set; }
        public byte bLevelMax { get; set; }
    }
}
