//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_RENTAL_ITEM
    {
        public string strUserID { get; set; }
        public string strAccountID { get; set; }
        public Nullable<byte> byRentalType { get; set; }
        public Nullable<byte> byRegType { get; set; }
        public Nullable<int> nRentalIndex { get; set; }
        public Nullable<int> nItemIndex { get; set; }
        public Nullable<short> sDurability { get; set; }
        public Nullable<long> nSerialNumber { get; set; }
        public Nullable<int> nRentalMoney { get; set; }
        public Nullable<short> sRentalTime { get; set; }
        public Nullable<short> sDuringTime { get; set; }
        public Nullable<System.DateTime> timeRental { get; set; }
        public Nullable<System.DateTime> timeRegister { get; set; }
    }
}
