//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DAILY_OP
    {
        public string strUserID { get; set; }
        public int ChaosMapTime { get; set; }
        public int UserRankRewardTime { get; set; }
        public int PersonalRankRewardTime { get; set; }
        public int KingWingTime { get; set; }
        public int WarderKillerTime1 { get; set; }
        public int WarderKillerTime2 { get; set; }
        public int KeeperKillerTime { get; set; }
        public int UserLoyaltyWingRewardTime { get; set; }
    }
}
