//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PERSONAL_RANK_OLD
    {
        public short nRank { get; set; }
        public string strPosition { get; set; }
        public short nElmoUP { get; set; }
        public string strElmoUserID { get; set; }
        public Nullable<int> nElmoLoyaltyMonthly { get; set; }
        public int nElmoCheck { get; set; }
        public short nKarusUP { get; set; }
        public string strKarusUserID { get; set; }
        public Nullable<int> nKarusLoyaltyMonthly { get; set; }
        public int nKarusCheck { get; set; }
        public int nSalary { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
