//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SAVED_MAGIC
    {
        public string strCharID { get; set; }
        public int nSkill1 { get; set; }
        public short nDuring1 { get; set; }
        public int nSkill2 { get; set; }
        public short nDuring2 { get; set; }
        public int nSkill3 { get; set; }
        public short nDuring3 { get; set; }
        public int nSkill4 { get; set; }
        public short nDuring4 { get; set; }
        public int nSkill5 { get; set; }
        public short nDuring5 { get; set; }
        public int nSkill6 { get; set; }
        public short nDuring6 { get; set; }
        public int nSkill7 { get; set; }
        public short nDuring7 { get; set; }
        public int nSkill8 { get; set; }
        public short nDuring8 { get; set; }
        public int nSkill9 { get; set; }
        public short nDuring9 { get; set; }
        public int nSkill10 { get; set; }
        public short nDuring10 { get; set; }
    }
}
