//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALIDATE
    {
        public string key { get; set; }
        public short type { get; set; }
        public string account { get; set; }
        public int timestamp { get; set; }
        public string fieldAlfa { get; set; }
        public string fieldBravo { get; set; }
        public string fieldCharlie { get; set; }
        public string fieldDelta { get; set; }
        public Nullable<int> fieldEcho { get; set; }
        public string fieldFoxtrot { get; set; }
    }
}
