//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOTE_REWARDS
    {
        public int id { get; set; }
        public int nCost { get; set; }
        public byte bItem { get; set; }
        public byte bGold { get; set; }
        public int nPrize { get; set; }
    }
}
