//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE_ITEMLER
    {
        public int dwid { get; set; }
        public Nullable<short> stacksize { get; set; }
        public Nullable<short> durability { get; set; }
        public string strUserId { get; set; }
        public Nullable<int> sira { get; set; }
        public string itembasicname { get; set; }
    }
}
