//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE
    {
        public string strAccountID { get; set; }
        public int nMoney { get; set; }
        public int dwTime { get; set; }
        public byte[] WarehouseData { get; set; }
        public byte[] strSerial { get; set; }
        public byte[] WarehouseDataTime { get; set; }
    }
}
