//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_rules
    {
        public int id { get; set; }
        public string paragraph { get; set; }
        public string text { get; set; }
        public Nullable<int> datetime { get; set; }
        public Nullable<int> list { get; set; }
    }
}
