//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_news
    {
        public int nid { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public int category { get; set; }
        public string author { get; set; }
        public System.DateTime datetime { get; set; }
        public int views { get; set; }
        public string forenlink { get; set; }
    }
}
