//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_ITEMMALL_LOG
    {
        public string strAccountID { get; set; }
        public string strCharID { get; set; }
        public short ServerNo { get; set; }
        public int ItemID { get; set; }
        public short ItemCount { get; set; }
        public System.DateTime BuyTime { get; set; }
        public string img_file_name { get; set; }
        public string strItemName { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> pay_type { get; set; }
        public int nExpirationTime { get; set; }
    }
}
