//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOCharp.Classes.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZONE_INFO
    {
        public byte ServerNo { get; set; }
        public short ZoneNo { get; set; }
        public string strZoneName { get; set; }
        public int InitX { get; set; }
        public int InitZ { get; set; }
        public int InitY { get; set; }
        public byte Type { get; set; }
        public byte RoomEvent { get; set; }
        public string bz { get; set; }
    }
}
